repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-symlinks
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-ast
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: debug-statements
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: [--max-line-length=127]
- repo: https://github.com/pre-commit/mirrors-yapf.git
  rev: v0.23.0
  hooks:
  - id: yapf
    files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
